---
- name: running java packaging for "{{ name }}"
  debug: 
    msg:  "{{ name }}" 
- name: check var2
  debug:
    msg: "{{ openjdk_url }}"
- name: check var3
  debug: 
    var: "raw_path"
- name: check var4
  debug:
    var: "os"
