---
- name: Linux Server side Java CPU
  hosts: linux_node
  diff: true 
  serial: 1
  gather_facts: false
  vars_files: 
    - vars.yaml
  tasks:
    - name: calling packaging tasks
      include: java_server_cpu_build.yaml
      vars:
        raw_path: "/home/cloud_user/raw"
        packing_path: "/home/clous_user/packing"
        packed_path: "/home/cloud_user/packed"
        os: "linux"
        name: "{{ item.name }}" 
      with_items: 
       - "{{ packages_linux }}"

- name: Ubuntu Server side Java CPU
  hosts: ubuntu_node
  vars_files: 
    - ./vars.yaml
  tasks:
    - name: calling packaging tasks
      include: java_server_cpu_build.yaml
      vars:
        raw_path: /home/ubuntu/raw
        packing_path: /home/ubuntu/packing 
        packed_path: /home/ubuntu/packed
        os: "ubuntu"
      with_items: 
       - "{{ packages_solaris }}"
