---
- name:  playbook ex1
  hosts: rce8
  become: true
  become_user: root
  tasks:
    - name: make  facts dir
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: copy facts files
      file:
        path: ../files/*
        dest: /etc/ansible/facts.d/
      
       
