---
- name: play to install packages on control machine
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - ../vars/packages.yaml
  tasks:
    - name: install dev packages
      package:
         name: "{{ dev_tools[ansible_os_family] | default(dev_tools['Default']) }}"
         state: present
      ignore_errors: true

- name: play to install the system admin packages 
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    -  ../vars/packages.yaml
  tasks:
    - name: install sys admin packages
      package:
        name: "{{ ops_tools[ansible_os_family] | default(ops_tools['Default']) }}"
        state: present
      ignore_errors: true
